### ISSUE TITLE
Give confirmation and extra info when logging

### ISSUE THREAD

**Issue by ndench** [nicored/gotickyourself#7]
After logging some time I don't get any output or confirmation. Would be good to get something like:

```
Logged 2 hours against: Development 

Daily summary (3h left):
2h development
1h tech debt
```
 So I get:
- confirmation the log happened
- a list of time I've logged today
- how many hours I have left to log for today

**Comment by nicored** [comment]
I improved it, and remaining hours is a good idea. I'll add it next

**Comment by nicored** [comment]
Completed
